#!/usr/bin/env python3
"""
species_check.py -- does a synthetic colony look like the species its label says?

WHY THIS FILE EXISTS (decision 3.68)
------------------------------------
Every earlier check in this repository asks whether a synthetic plate is
REALISTIC. None of them asks whether it is CORRECT.

That distinction is the whole multi-class half of the paper. The generator is
handed a label -- "P.aeruginosa at (942, 337)" -- and paints something. If it
paints a convincing colony of the WRONG species, then:

  * the plate passes every existing gate (zero label error, no ghost colonies,
    looks real), and
  * per-class AP on the substitution curve is measuring nothing, and
  * the S100 arm scores badly, and the paper concludes "synthetic data does not
    substitute" when the true finding is "the generator ignored the class".

Those two conclusions are different claims and must never be confused. So the
class channel gets its own measurement, before Phase 4 spends a single GPU-hour.

WHAT IS MEASURED
----------------
Three appearance statistics, on the INNER 35 % DISC of each labelled box:

    yellowness   R - B channel difference. S.aureus is by far the yellowest
                 species in AGAR; this separates it from everything else.
    contrast     mean grey inside the colony minus the median grey of the
                 surrounding medium. P.aeruginosa is the faint one -- it is
                 nearly invisible against the agar, and that is its signature.
    texture      Laplacian standard deviation. Distinguishes a smooth, mucoid
                 colony from a filamentous one.

The inner disc, not the whole box: the box edge contains the colony rim and the
medium, and their gradient swamps everything. An earlier version of this
measurement used the whole mask, reported "synthetic texture 26.7 vs real 25.3",
and concluded texture was fine. On the inner disc the same data reads 5.8 vs 1.5.
The first number was measuring edges.

THE TWO VERDICTS
----------------
1. ORDERING. Rank the classes by each statistic, in the real data and in the
   generated data, and compare the two rankings (Spearman). This answers "is the
   class channel alive at all?" -- it is robust to the generator being uniformly
   too pale or too grainy, which a per-class ratio is not.

2. SEPARABILITY. The smallest distance between any two class centroids, in
   units of within-class spread. This answers "could a classifier tell these
   apart?" If real separability is 3.0 and generated is 0.4, the classes have
   collapsed into one appearance -- even if the ordering test passes.

Both are reported with a PLATE-LEVEL bootstrap interval, because colonies on one
plate share a plate, a camera and a batch of medium; a colony-level interval
would be dishonestly narrow (this is the same argument as decision 3.17).

WHY THE LEVEL MATTERS (decision 3.2 / 3.7)
------------------------------------------
Synthetic data for level L was generated by a LoRA trained only on level L's
subset. Comparing it against the FULL real set would let the comparison see real
data the generator never had -- the same leakage the rest of Phase 3 is built to
prevent. So --level is required, and the real side is restricted to that level's
train list.

USAGE
    python src/generate/species_check.py --level 100 \
        --generated data/synthetic/tur_testi \
        --list data/processed/lists/train.txt \
        --out results/species_100.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np

# Fraction of the box side used as the measurement disc radius. 0.35 keeps the
# disc clear of the colony rim for a circular colony that fills its box.
INNER = 0.35

# Boxes smaller than this cannot support a meaningful inner disc. They are
# COUNTED and REPORTED, never silently dropped (design principle 2).
MIN_BOX_PX = 12

# A class with fewer than this many colonies does not get a number. Reporting a
# median of four objects as if it were an estimate is how a project talks itself
# into a false conclusion.
MIN_N = 15

# Ratio beyond which a statistic is flagged. Not a hard rule -- a flag asks for
# eyes, it does not stop the program, because "too grainy" is a research finding
# and not a bug.
FLAG_RATIO = 2.0

BOOTSTRAP = 2000


# ---------------------------------------------------------------------------
# measurement
# ---------------------------------------------------------------------------

def plate_stats(img_path: Path, lab_path: Path, classes: list[str],
                counters: dict) -> list[dict]:
    """Appearance statistics for every labelled colony on one plate."""
    im = cv2.imread(str(img_path))
    if im is None:
        counters["missing_image"] += 1
        return []
    if not lab_path.exists():
        counters["missing_label"] += 1
        return []

    H, W = im.shape[:2]
    grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    lap = cv2.Laplacian(grey.astype(np.float32), cv2.CV_32F, ksize=3)
    out = []

    for line in lab_path.read_text().splitlines():
        p = line.split()
        if not p:
            continue
        c = int(p[0])
        if c >= len(classes):
            sys.exit(f"ERROR: {lab_path} has class id {c} but classes.txt lists "
                     f"{len(classes)}. The two are out of sync; every number "
                     f"below would be attributed to the wrong species.")
        x, y, w, h = (float(t) for t in p[1:5])
        x0, y0 = int((x - w / 2) * W), int((y - h / 2) * H)
        x1, y1 = int((x + w / 2) * W), int((y + h / 2) * H)
        cx0, cy0 = max(0, x0), max(0, y0)
        cx1, cy1 = min(W, x1), min(H, y1)
        if (cx0, cy0, cx1, cy1) != (x0, y0, x1, y1):
            counters["clipped"] += 1
        if cx1 - cx0 < MIN_BOX_PX or cy1 - cy0 < MIN_BOX_PX:
            counters["too_small"] += 1
            continue

        box = im[cy0:cy1, cx0:cx1]
        disc = np.zeros(box.shape[:2], np.uint8)
        r = max(2, int(min(box.shape[:2]) * INNER))
        cv2.circle(disc, (box.shape[1] // 2, box.shape[0] // 2), r, 255, -1)
        m = disc > 0
        if m.sum() < 20:
            counters["too_small"] += 1
            continue

        # Local medium: a frame around the box. The median resists the case
        # where a neighbouring colony intrudes into the frame.
        pad = int(max(box.shape[:2]) * 0.6)
        fy0, fy1 = max(0, cy0 - pad), min(H, cy1 + pad)
        fx0, fx1 = max(0, cx0 - pad), min(W, cx1 + pad)
        medium = float(np.median(grey[fy0:fy1, fx0:fx1]))

        col = box[m].mean(axis=0)                      # B, G, R
        out.append({
            "cls": classes[c],
            "plate": img_path.stem,
            "diameter": int(cx1 - cx0),
            "yellowness": float(col[2] - col[0]),
            "contrast": float(grey[cy0:cy1, cx0:cx1][m].mean() - medium),
            "texture": float(lap[cy0:cy1, cx0:cx1][m].std()),
        })
    return out


STATS = ("yellowness", "contrast", "texture")


def by_class(rows: list[dict]) -> dict:
    d: dict[str, list[dict]] = {}
    for r in rows:
        d.setdefault(r["cls"], []).append(r)
    return d


def medians(rows: list[dict]) -> dict:
    """Per-class median of each statistic, for classes with enough colonies."""
    out = {}
    for cls, v in by_class(rows).items():
        if len(v) < MIN_N:
            continue
        out[cls] = {s: float(np.median([r[s] for r in v])) for s in STATS}
        out[cls]["n"] = len(v)
        out[cls]["diameter"] = float(np.median([r["diameter"] for r in v]))
    return out


# ---------------------------------------------------------------------------
# verdict 1: is the class channel alive?
# ---------------------------------------------------------------------------

def spearman(a: list[float], b: list[float]) -> float:
    """Rank correlation. Written out rather than pulled from scipy: this repo
    has no scipy dependency and the formula is four lines."""
    n = len(a)
    if n < 3:
        return float("nan")
    ra = np.argsort(np.argsort(a)).astype(float)
    rb = np.argsort(np.argsort(b)).astype(float)
    ra -= ra.mean(); rb -= rb.mean()
    denom = float(np.sqrt((ra ** 2).sum() * (rb ** 2).sum()))
    return float((ra * rb).sum() / denom) if denom else float("nan")


def ordering(real_med: dict, gen_med: dict) -> dict:
    """Per statistic: does the generated data rank the classes as reality does?"""
    shared = sorted(set(real_med) & set(gen_med))
    out = {"classes": shared}
    for s in STATS:
        out[s] = spearman([real_med[c][s] for c in shared],
                          [gen_med[c][s] for c in shared])
    return out


# ---------------------------------------------------------------------------
# verdict 2: could a classifier tell the classes apart?
# ---------------------------------------------------------------------------

def separability(rows: list[dict], shared: list[str],
                 stats: tuple = STATS) -> float:
    """
    Smallest between-class centroid distance, in units of within-class spread,
    over (yellowness, contrast, texture) standardised on the pooled data.

    This is a crude Fisher-style ratio, and deliberately so: the point is to
    compare the SAME quantity between real and generated, not to estimate a
    classifier's accuracy. A number that is 5x smaller on the generated side
    means the appearances have collapsed together, whatever the constant is.
    """
    d = by_class(rows)
    usable = [c for c in shared if c in d and len(d[c]) >= MIN_N]
    if len(usable) < 2:
        return float("nan")
    allv = np.array([[r[s] for s in stats] for r in rows], dtype=float)
    sd = allv.std(axis=0)
    sd[sd == 0] = 1.0
    cent, spread = {}, {}
    for c in usable:
        v = np.array([[r[s] for s in stats] for r in d[c]], dtype=float) / sd
        cent[c] = v.mean(axis=0)
        spread[c] = float(np.sqrt((v.std(axis=0) ** 2).sum())) or 1e-6
    best = float("inf")
    for i, a in enumerate(usable):
        for b in usable[i + 1:]:
            dist = float(np.linalg.norm(cent[a] - cent[b]))
            best = min(best, dist / (0.5 * (spread[a] + spread[b])))
    return best


def plate_bootstrap(rows: list[dict], shared: list[str], rng,
                    stats: tuple = STATS) -> tuple:
    """
    Plate-level bootstrap of `separability`. Plates are the resampling unit,
    not colonies: colonies on one plate share a plate, a camera and a batch of
    medium, so resampling colonies would pretend we have far more independent
    observations than we do (decision 3.17).
    """
    plates = sorted({r["plate"] for r in rows})
    if len(plates) < 3:
        return (float("nan"), float("nan"), len(plates))
    idx: dict[str, list[dict]] = {p: [] for p in plates}
    for r in rows:
        idx[r["plate"]].append(r)
    vals = []
    for _ in range(BOOTSTRAP):
        pick = rng.choice(len(plates), len(plates), replace=True)
        sample = [r for i in pick for r in idx[plates[i]]]
        v = separability(sample, shared, stats)
        if not np.isnan(v):
            vals.append(v)
    if not vals:
        return (float("nan"), float("nan"), len(plates))
    return (float(np.percentile(vals, 5)), float(np.percentile(vals, 95)),
            len(plates))


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--level", type=int, required=True, choices=[10, 25, 50, 100],
                    help="which data level the generated plates belong to "
                         "(decision 3.7 -- there is no default on purpose)")
    ap.add_argument("--generated", required=True,
                    help="inpaint.py run output (images/ + labels/)")
    ap.add_argument("--list", required=True,
                    help="the REAL train list of THIS level, e.g. "
                         "data/processed/lists/train_25.txt")
    ap.add_argument("--data", default="data/processed")
    ap.add_argument("--classes", default="data/processed/classes.txt")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", default=None, help="write the full result as JSON")
    args = ap.parse_args()

    classes = Path(args.classes).read_text().split()
    lst = Path(args.list)
    if not lst.exists():
        sys.exit(f"ERROR: {lst} not found.")

    # Decision 3.7: the level must be visible in what we compare against. The
    # 100 % level is the plain train.txt; every other level carries its number.
    if args.level != 100 and f"_{args.level}" not in lst.name:
        sys.exit(f"ERROR (decision 3.7): --level {args.level} was given but the "
                 f"real list is {lst.name}. Comparing level-{args.level} "
                 f"synthetic data against a different real subset lets the "
                 f"comparison see data the generator never had.")

    counters = {"missing_image": 0, "missing_label": 0,
                "clipped": 0, "too_small": 0}

    data = Path(args.data)
    # The split lists hold absolute image paths (make_splits.py). Those paths
    # are only valid on the machine that wrote them, so the listed path is used
    # when it resolves and the stem is used otherwise -- a list produced on
    # another box must not silently measure zero colonies.
    entries = [s.strip() for s in lst.read_text().splitlines() if s.strip()]
    real = []
    for e in entries:
        stem = Path(e).stem
        img = Path(e)
        if not img.exists():
            img = data / "images" / f"{stem}.jpg"
        real += plate_stats(img, data / "labels" / f"{stem}.txt",
                            classes, counters)

    gen_dir = Path(args.generated)
    gen = []
    for img in sorted((gen_dir / "images").glob("*.jpg")):
        gen += plate_stats(img, gen_dir / "labels" / f"{img.stem}.txt",
                           classes, counters)

    if not real:
        sys.exit(f"ERROR: no real colonies measured from {lst}.")
    if not gen:
        sys.exit(f"ERROR: no synthetic colonies measured from {gen_dir}. "
                 f"Expected {gen_dir}/images/*.jpg with matching labels/.")

    rmed, gmed = medians(real), medians(gen)
    shared = sorted(set(rmed) & set(gmed))

    # Design principle 2: a class that falls out of the comparison must SAY so.
    # Silently reporting three species when the label file named five reads as
    # "all five were checked".
    for side, med, rows in (("real", rmed, real), ("synthetic", gmed, gen)):
        seen = {c: len(v) for c, v in by_class(rows).items()}
        dropped = {c: n for c, n in seen.items() if c not in med}
        if dropped:
            print(f"[!] {side}: not compared, fewer than {MIN_N} colonies -> "
                  + ", ".join(f"{c}({n})" for c, n in sorted(dropped.items())))
    only = (set(rmed) | set(gmed)) - set(shared)
    if only:
        print(f"[!] present on one side only: {', '.join(sorted(only))}")
    if not shared:
        sys.exit(f"ERROR: no class has >= {MIN_N} colonies on BOTH sides. "
                 f"real={ {c: v['n'] for c, v in rmed.items()} } "
                 f"generated={ {c: v['n'] for c, v in gmed.items()} }. "
                 f"Generate more plates rather than lowering MIN_N.")

    # ---- per-class table --------------------------------------------------
    print(f"[species] level={args.level}  real {len(real)} colonies / "
          f"{len(entries)} plates   synthetic {len(gen)} colonies")
    print(f"          measured on the inner {INNER:.0%} disc of each box\n")
    head = f"{'species':14s} {'n(r/g)':>9} {'diam px':>9}"
    for s in STATS:
        head += f" {s[:9]:>17s}"
    print(head)
    print("-" * len(head))
    flagged = []
    for c in shared:
        row = f"{c:14s} {rmed[c]['n']:>4}/{gmed[c]['n']:<4} " \
              f"{rmed[c]['diameter']:>4.0f}/{gmed[c]['diameter']:<4.0f}"
        for s in STATS:
            r, g = rmed[c][s], gmed[c][s]
            mark = ""
            if abs(r) > 1e-6:
                ratio = g / r
                if ratio > FLAG_RATIO or ratio < 1 / FLAG_RATIO:
                    mark = " !"
                    flagged.append((c, s, round(ratio, 2)))
            row += f" {r:>7.1f}->{g:<7.1f}{mark:<2s}"
        print(row)

    # ---- verdict 1 --------------------------------------------------------
    orde = ordering(rmed, gmed)
    print(f"\n1) ORDERING -- is the class channel alive? "
          f"(rank correlation over {len(shared)} classes, 1.0 = identical order)")
    for s in STATS:
        v = orde[s]
        verdict = ("channel works" if v >= 0.8 else
                   "weak" if v >= 0.4 else "NO class signal")
        print(f"   {s:12s} {v:+.2f}   {verdict}")

    # ---- verdict 2 --------------------------------------------------------
    rng = np.random.default_rng(args.seed)
    rsep = separability(real, shared)
    gsep = separability(gen, shared)
    rlo, rhi, rp = plate_bootstrap(real, shared, rng)
    glo, ghi, gp = plate_bootstrap(gen, shared, rng)
    # Same measure with the texture axis removed. Texture is the statistic the
    # generator gets wrong (decision 3.67), and being wrong in a class-dependent
    # way INFLATES separability -- the classes would be told apart by an
    # artefact. Colour and contrast are the axes reality actually uses.
    COLOUR = ("yellowness", "contrast")
    rsep_c = separability(real, shared, COLOUR)
    gsep_c = separability(gen, shared, COLOUR)
    print(f"\n2) SEPARABILITY -- could a classifier tell the classes apart? "
          f"(closest pair, in within-class spreads)")
    print(f"   real       {rsep:.2f}   (90% CI {rlo:.2f}-{rhi:.2f}, "
          f"{rp} plates)")
    print(f"   synthetic  {gsep:.2f}   (90% CI {glo:.2f}-{ghi:.2f}, "
          f"{gp} plates)")
    if not np.isnan(rsep) and rsep > 0:
        print(f"   retained   {gsep / rsep:.0%} of the real separation")
    print(f"   without the texture axis (colour + contrast only):")
    print(f"   real       {rsep_c:.2f}      synthetic  {gsep_c:.2f}", end="")
    if not np.isnan(rsep_c) and rsep_c > 0:
        print(f"      retained {gsep_c / rsep_c:.0%}")
    else:
        print()

    # ---- what to do with this --------------------------------------------
    if flagged:
        print(f"\n[!] {len(flagged)} statistic(s) off by more than {FLAG_RATIO}x:")
        for c, s, r in flagged:
            print(f"      {c:14s} {s:12s} x{r}")
        print("    A systematic offset in ONE statistic across ALL classes is a "
              "shortcut cue:\n    the detector can learn it instead of learning "
              "colonies, and the S100 arm\n    then measures the cue, not the "
              "substitution (decision 3.67).")
    if gp < 3 or rp < 3:
        print(f"\n[!] Fewer than 3 plates on one side; the bootstrap interval "
              f"is not defined.\n    These medians pick a direction, not a value.")

    for k, v in counters.items():
        if v:
            print(f"[count] {k}: {v}")

    if args.out:
        p = Path(args.out)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps({
            "level": args.level,
            "real_list": str(lst),
            "generated": str(gen_dir),
            "inner_disc": INNER,
            "min_n": MIN_N,
            "real": rmed, "generated": gmed,
            "ordering": orde,
            "separability": {
                "real": rsep, "real_ci90": [rlo, rhi], "real_plates": rp,
                "generated": gsep, "generated_ci90": [glo, ghi],
                "generated_plates": gp,
                "real_no_texture": rsep_c, "generated_no_texture": gsep_c,
            },
            "flagged": [{"cls": c, "stat": s, "ratio": r} for c, s, r in flagged],
            "counters": counters,
        }, indent=2))
        print(f"\n-> {p}")


if __name__ == "__main__":
    main()
