#!/usr/bin/env python3
"""
Build the training-set list of every synthetic arm.                    (3.101)

WHY THIS EXISTS
---------------
Until now `train.py` DERIVED its training set from `--level`: level 25 meant
`lists/train_25.txt`, and that was the whole vocabulary. The synthetic arms of
Phase 6 cannot be said in it. A "+S" arm trains on a real subset PLUS synthetic
plates, topped up to the full-data size, and no `--level` names that.

So the arm becomes a LIST, and the list carries its own description:

    data/processed/lists/arm_<name>.txt        the paths Ultralytics reads
    data/processed/lists/arm_<name>.txt.json   what went into it

`train.py --train-list <path>` reads both and copies the composition into
`run_metrics.json`, so `results/table.csv` ends up carrying n_real and n_synth
per run. That matters because the substitution curve is a statement ABOUT those
two numbers: reporting an arm without them would be reporting the answer
without the question.

WHAT THE ARMS ARE
-----------------
From `scripts/budget.py`. Every "+S" arm tops its training set up to the full
data size, so its synthetic share is (1.00 - real share):

    arm            real level   real   synth   total
    S100              100          0    2987    2987
    G10+S              10        299    2688    2987
    G25+S              25        746    2240    2986
    G50+S              50       1491    1494    2985
    G25+S_0.5x         25        746    1120    1866
    G25+S_2x           25        746    4481    5227

EACH ARM DRAWS FROM ITS OWN LEVEL'S POOL -- decisions 3.2 and 3.7. The pool for
a G25 arm was generated by the LoRA trained on the 25% subset; using the
level-100 pool would put information from images outside that subset into the
arm's training data, which is the leak the per-level protocol exists to
prevent. This script therefore refuses to substitute one pool for another, even
when the wanted pool is not finished and another one is.

NESTED SUBSETS, ON PURPOSE
--------------------------
The amount sweep (1120 / 2240 / 4481 synthetic plates on the same G25 base)
takes the FIRST N of one sorted pool, so the smaller arms are subsets of the
larger. The sweep asks what changes when the QUANTITY of synthetic data
changes; drawing three independent pools would let generation-to-generation
variation ride along with quantity and confound the two.

Deterministic for the same reason: sorted order, no shuffling. Re-running this
script cannot change an arm that has already been trained.

PARTIAL POOLS ARE NORMAL
------------------------
Generation runs for tens of hours, so this script is expected to be called
while it is still going (gen_queue.sh calls it after every level). An arm whose
pool is short is SKIPPED, not failed, and reported as waiting. Nothing is
written for it, so run_queue.sh will simply not find its list yet and will try
again later.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed"
LISTS = DATA / "lists"
GEN = ROOT / "src" / "generate"

# The full-data training size. Not hard-coded as a constant on faith: read from
# the level-100 list, so that if the splits are ever rebuilt this file cannot
# quietly disagree with them.
FULL_LIST = LISTS / "train.txt"

# (arm, real level, real share, synthetic share)
ARMS = [
    ("S100",       100, 0.00, 1.00),
    ("G10+S",       10, 0.10, 0.90),
    ("G25+S",       25, 0.25, 0.75),
    ("G50+S",       50, 0.50, 0.50),
    ("G25+S_0.5x",  25, 0.25, 0.375),
    ("G25+S_2x",    25, 0.25, 1.50),
]


def real_list(level: int) -> Path:
    return LISTS / ("train.txt" if level == 100 else f"train_{level}.txt")


def read_lines(p: Path) -> list[str]:
    return [x.strip() for x in p.read_text(encoding="utf-8").splitlines() if x.strip()]


def synth_pool(level: int) -> tuple[Path, list[Path]]:
    """The level's synthetic plates, sorted, and only those with a label."""
    d = GEN / f"synth_g{level}"
    imgs = sorted((d / "images").glob("*.jpg")) if (d / "images").is_dir() else []
    # A plate whose label is missing would train the model on 'this image has no
    # colonies' -- the silent failure validate_list() in train.py exists to
    # catch. Filter here so the list never contains one in the first place.
    good, orphan = [], 0
    for ip in imgs:
        lp = d / "labels" / (ip.stem + ".txt")
        if lp.exists():
            good.append(ip)
        else:
            orphan += 1
    if orphan:
        print(f"  [!] level {level}: {orphan} images have no label and were "
              f"left out of the pool")
    return d, good


def main() -> int:
    if not FULL_LIST.exists():
        sys.exit(f"ERROR: {FULL_LIST} not found. Run src/make_splits.py first.")
    full_n = len(read_lines(FULL_LIST))
    print(f"full training size: {full_n} images  ({FULL_LIST.name})")

    LISTS.mkdir(parents=True, exist_ok=True)
    built, waiting = [], []

    for arm, level, real_share, synth_share in ARMS:
        want_synth = round(synth_share * full_n)
        rl = real_list(level)
        if not rl.exists():
            print(f"{arm:12} SKIP -- {rl.name} missing")
            continue
        reals = read_lines(rl) if real_share > 0 else []

        pool_dir, pool = synth_pool(level)
        if len(pool) < want_synth:
            print(f"{arm:12} waiting -- needs {want_synth} synthetic plates "
                  f"from {pool_dir.name}, has {len(pool)}")
            waiting.append((arm, want_synth - len(pool)))
            continue

        synths = [str(p) for p in pool[:want_synth]]      # nested: first N
        out = LISTS / f"arm_{arm.replace('+', 'plus')}.txt"
        out.write_text("\n".join(reals + synths) + "\n", encoding="utf-8")

        side = {
            "arm": arm,
            "level": level,
            "real_share": real_share,
            "synth_share": synth_share,
            "n_real": len(reals),
            "n_synth": len(synths),
            "n_total": len(reals) + len(synths),
            "real_list": str(rl),
            "synth_source": str(pool_dir),
            "synth_pool_size": len(pool),
            "selection": "first N of the sorted pool (nested subsets, 3.101)",
            "full_training_size": full_n,
            "built_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        out.with_suffix(out.suffix + ".json").write_text(
            json.dumps(side, indent=2), encoding="utf-8")

        print(f"{arm:12} OK -- {len(reals)} real + {len(synths)} synthetic "
              f"= {side['n_total']}  -> {out.name}")
        built.append(arm)

    print(f"\n{len(built)} arms built, {len(waiting)} waiting on generation")
    for arm, short in waiting:
        print(f"  {arm}: {short} more plates needed")
    # Exit 0 even with arms waiting: this script is called repeatedly while
    # generation runs, and "not yet" is not an error.
    return 0


if __name__ == "__main__":
    sys.exit(main())
